// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwk5OcsJHEQnwD5JTWmPJxUeGEgRVx0HE',
    appId: '1:962259877408:web:b81e39dbd852a211af8645',
    messagingSenderId: '962259877408',
    projectId: 'chat-app-8ddbc',
    authDomain: 'chat-app-8ddbc.firebaseapp.com',
    storageBucket: 'chat-app-8ddbc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXC9IPgVQxoKWALcuEbhd5Sp2pBMeCkRw',
    appId: '1:962259877408:android:2e494ca3fb373d71af8645',
    messagingSenderId: '962259877408',
    projectId: 'chat-app-8ddbc',
    storageBucket: 'chat-app-8ddbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNiK44v48Z6TiK0hz5z-llM2PHeZO98Gw',
    appId: '1:962259877408:ios:a27ecc6e278d805caf8645',
    messagingSenderId: '962259877408',
    projectId: 'chat-app-8ddbc',
    storageBucket: 'chat-app-8ddbc.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNiK44v48Z6TiK0hz5z-llM2PHeZO98Gw',
    appId: '1:962259877408:ios:04dad0c280f8a3d7af8645',
    messagingSenderId: '962259877408',
    projectId: 'chat-app-8ddbc',
    storageBucket: 'chat-app-8ddbc.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
